
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 18:13:50 IST (Sep  5 2019 12:43:50 UTC)

// Verification Directory fv/f1 

module f1(a, b, c, d, out);
  input a, b, c, d;
  output out;
  wire a, b, c, d;
  wire out;
  AO22X1 g20(.A0 (d), .A1 (c), .B0 (b), .B1 (a), .Y (out));
endmodule

