
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Oct 22 2019 23:30:53 IST (Oct 22 2019 18:00:53 UTC)

// Verification Directory fv/serial_multiplier 

module serial_multiplier(clk, rst, a, b, P);
  input clk, rst;
  input [3:0] a, b;
  output [7:0] P;
  wire clk, rst;
  wire [3:0] a, b;
  wire [7:0] P;
  wire [7:0] z;
  wire [3:0] x;
  wire [2:0] i;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  DFFRHQX1 \z_reg[7] (.RN (n_31), .CK (clk), .D (n_30), .Q (z[7]));
  SDFFQXL \P_reg[0] (.CK (clk), .D (P[0]), .SI (z[0]), .SE (n_27), .Q
       (P[0]));
  SDFFRHQX1 \z_reg[6] (.RN (n_31), .CK (clk), .D (n_29), .SI (n_21),
       .SE (n_28), .Q (z[6]));
  AO22XL g1458(.A0 (n_29), .A1 (n_28), .B0 (n_18), .B1 (z[7]), .Y
       (n_30));
  SDFFQXL \P_reg[1] (.CK (clk), .D (P[1]), .SI (z[1]), .SE (n_27), .Q
       (P[1]));
  SDFFRHQX1 \z_reg[5] (.RN (n_31), .CK (clk), .D (n_25), .SI (n_24),
       .SE (n_26), .Q (z[5]));
  DFFRHQX1 \z_reg[0] (.RN (n_31), .CK (clk), .D (z[1]), .Q (z[0]));
  SDFFQXL \P_reg[2] (.CK (clk), .D (P[2]), .SI (z[2]), .SE (n_27), .Q
       (P[2]));
  OAI22X1 g1460(.A0 (n_26), .A1 (n_25), .B0 (n_16), .B1 (n_17), .Y
       (n_28));
  DFFSRHQX1 \x_reg[0] (.RN (n_12), .SN (n_3), .CK (clk), .D (x[1]), .Q
       (x[0]));
  DFFRHQX1 \z_reg[1] (.RN (n_31), .CK (clk), .D (z[2]), .Q (z[1]));
  SDFFQXL \P_reg[3] (.CK (clk), .D (P[3]), .SI (z[3]), .SE (n_27), .Q
       (P[3]));
  INVXL g1466(.A (n_25), .Y (n_24));
  DFFSRHQX1 \x_reg[1] (.RN (n_7), .SN (n_1), .CK (clk), .D (x[2]), .Q
       (x[1]));
  SDFFQXL \P_reg[6] (.CK (clk), .D (P[6]), .SI (z[6]), .SE (n_27), .Q
       (P[6]));
  SDFFQXL \P_reg[5] (.CK (clk), .D (P[5]), .SI (z[5]), .SE (n_27), .Q
       (P[5]));
  SDFFQXL \P_reg[7] (.CK (clk), .D (P[7]), .SI (z[7]), .SE (n_27), .Q
       (P[7]));
  SDFFQXL \P_reg[4] (.CK (clk), .D (P[4]), .SI (z[4]), .SE (n_27), .Q
       (P[4]));
  SDFFRHQX1 \z_reg[4] (.RN (n_31), .CK (clk), .D (n_23), .SI (n_20),
       .SE (n_22), .Q (z[4]));
  AOI22X1 g1468(.A0 (n_23), .A1 (n_22), .B0 (n_19), .B1 (z[5]), .Y
       (n_25));
  DFFRHQX1 \z_reg[2] (.RN (n_31), .CK (clk), .D (z[3]), .Q (z[2]));
  DFFSRHQX1 \x_reg[2] (.RN (n_11), .SN (n_4), .CK (clk), .D (x[3]), .Q
       (x[2]));
  SDFFRHQX1 \z_reg[3] (.RN (n_31), .CK (clk), .D (n_15), .SI (n_9), .SE
       (z[4]), .Q (z[3]));
  INVXL g1479(.A (n_29), .Y (n_21));
  CLKINVX1 g1478(.A (n_20), .Y (n_23));
  MXI2XL g1484(.A (n_6), .B (n_19), .S0 (z[5]), .Y (n_22));
  AND2X4 g1483(.A (n_14), .B (n_31), .Y (n_27));
  DFFSRHQX1 \x_reg[3] (.RN (n_8), .SN (n_2), .CK (clk), .D (x[0]), .Q
       (x[3]));
  SDFFRHQX1 \i_reg[2] (.RN (n_31), .CK (clk), .D (n_13), .SI (i[2]),
       .SE (n_0), .Q (i[2]));
  MXI2XL g1486(.A (n_10), .B (n_18), .S0 (z[7]), .Y (n_29));
  MXI2XL g1485(.A (n_17), .B (z[6]), .S0 (n_16), .Y (n_26));
  NAND2XL g1489(.A (n_15), .B (z[4]), .Y (n_20));
  SDFFRHQX1 \i_reg[1] (.RN (n_31), .CK (clk), .D (i[0]), .SI (n_5), .SE
       (i[1]), .Q (i[1]));
  NOR3X1 g1488(.A (i[1]), .B (i[0]), .C (n_13), .Y (n_14));
  OR2X1 g1494(.A (a[0]), .B (n_31), .Y (n_12));
  OR2X1 g1501(.A (a[2]), .B (n_31), .Y (n_11));
  CLKINVX1 g1491(.A (n_10), .Y (n_18));
  CLKINVX1 g1499(.A (n_9), .Y (n_15));
  OR2X1 g1503(.A (a[3]), .B (n_31), .Y (n_8));
  OR2X1 g1502(.A (a[1]), .B (n_31), .Y (n_7));
  CLKINVX1 g1490(.A (n_6), .Y (n_19));
  NAND2XL g1493(.A (a[2]), .B (rst), .Y (n_4));
  NAND2XL g1492(.A (a[0]), .B (rst), .Y (n_3));
  NAND2XL g1495(.A (b[2]), .B (x[0]), .Y (n_16));
  NAND2XL g1496(.A (b[1]), .B (x[0]), .Y (n_6));
  NAND2XL g1500(.A (a[3]), .B (rst), .Y (n_2));
  NAND2XL g1504(.A (a[1]), .B (rst), .Y (n_1));
  NAND2XL g1505(.A (i[1]), .B (i[0]), .Y (n_0));
  NAND2XL g1506(.A (b[0]), .B (x[0]), .Y (n_9));
  NAND2XL g1497(.A (b[3]), .B (x[0]), .Y (n_10));
  CLKINVX1 g1507(.A (z[6]), .Y (n_17));
  CLKINVX1 g1508(.A (i[2]), .Y (n_13));
  CLKINVX2 g1510(.A (rst), .Y (n_31));
  DFFRX1 \i_reg[0] (.RN (n_31), .CK (clk), .D (n_5), .Q (i[0]), .QN
       (n_5));
endmodule

