
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Oct 22 2019 22:48:59 IST (Oct 22 2019 17:18:59 UTC)

// Verification Directory fv/dff 

module dff(d, clk, rst, q);
  input d, clk, rst;
  output q;
  wire d, clk, rst;
  wire q;
  wire n_0;
  DFFQXL q_reg(.CK (clk), .D (n_0), .Q (q));
  NOR2BX1 g5(.AN (d), .B (rst), .Y (n_0));
endmodule

