
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 15 2019 08:50:41 IST (Sep 15 2019 03:20:41 UTC)

// Verification Directory fv/encoder8x3 

module encoder8x3(a0, a1, a2, a3, a4, a5, a6, a7, x0, x1, x2, en);
  input a0, a1, a2, a3, a4, a5, a6, a7, en;
  output x0, x1, x2;
  wire a0, a1, a2, a3, a4, a5, a6, a7, en;
  wire x0, x1, x2;
  wire n_0, n_1, n_2, n_3, n_4, n_6;
  NAND2XL g223(.A (n_0), .B (n_6), .Y (x1));
  NAND2XL g224(.A (n_3), .B (n_6), .Y (x2));
  NAND2XL g222(.A (n_1), .B (n_4), .Y (x0));
  AOI21XL g228(.A0 (en), .A1 (a6), .B0 (n_2), .Y (n_6));
  OAI31XL g225(.A0 (a1), .A1 (a3), .A2 (a5), .B0 (en), .Y (n_4));
  OAI21XL g226(.A0 (a4), .A1 (a5), .B0 (en), .Y (n_3));
  INVXL g229(.A (n_1), .Y (n_2));
  OAI21XL g227(.A0 (a2), .A1 (a3), .B0 (en), .Y (n_0));
  NAND2XL g230(.A (en), .B (a7), .Y (n_1));
endmodule

