
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 27 2019 22:23:55 IST (Sep 27 2019 16:53:55 UTC)

// Verification Directory fv/fullAdder 

module fullAdder(a, b, c, s_out, c_out);
  input a, b, c;
  output s_out, c_out;
  wire a, b, c;
  wire s_out, c_out;
  ADDFXL g54(.A (a), .B (b), .CI (c), .CO (c_out), .S (s_out));
endmodule

