/*
###############################################################
#  Generated by:      Cadence Innovus 16.21-s078_1
#  OS:                Linux x86_64(Host ID client03)
#  Generated on:      Thu Sep  5 22:57:22 2019
#  Design:            f2
#  Command:           saveNetlist f2_netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 18:29:54 IST (Sep  5 2019 12:59:54 UTC)
// Verification Directory fv/f2 
module f2 (
	a, 
	b, 
	c, 
	d, 
	e, 
	f, 
	out);
   input a;
   input b;
   input c;
   input d;
   input e;
   input f;
   output out;

   // Internal wires
   wire n_0;

   NOR2BXL g48 (.AN(f),
	.B(n_0),
	.Y(out));
   AOI32XL g49 (.A0(c),
	.A1(b),
	.A2(a),
	.B0(d),
	.B1(e),
	.Y(n_0));
endmodule

