
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Nov  9 2019 20:11:20 IST (Nov  9 2019 14:41:20 UTC)

// Verification Directory fv/univShiftReg 

module univShiftReg(CLK, INP, OUT, select, leftInp, rightInp);
  input CLK, leftInp, rightInp;
  input [3:0] INP;
  input [1:0] select;
  output [3:0] OUT;
  wire CLK, leftInp, rightInp;
  wire [3:0] INP;
  wire [1:0] select;
  wire [3:0] OUT;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  DFFQX1 \tmp_reg[0] (.CK (CLK), .D (n_15), .Q (OUT[0]));
  DFFQX1 \tmp_reg[1] (.CK (CLK), .D (n_14), .Q (OUT[1]));
  DFFQX1 \tmp_reg[2] (.CK (CLK), .D (n_13), .Q (OUT[2]));
  DFFQX1 \tmp_reg[3] (.CK (CLK), .D (n_12), .Q (OUT[3]));
  NAND2XL g304(.A (n_5), .B (n_11), .Y (n_15));
  NAND2XL g305(.A (n_4), .B (n_10), .Y (n_14));
  NAND2XL g302(.A (n_0), .B (n_6), .Y (n_13));
  NAND2XL g303(.A (n_1), .B (n_7), .Y (n_12));
  AOI22XL g308(.A0 (n_9), .A1 (INP[0]), .B0 (OUT[0]), .B1 (n_8), .Y
       (n_11));
  AOI22XL g313(.A0 (n_9), .A1 (INP[1]), .B0 (OUT[1]), .B1 (n_8), .Y
       (n_10));
  AOI22XL g312(.A0 (n_9), .A1 (INP[3]), .B0 (OUT[3]), .B1 (n_8), .Y
       (n_7));
  AOI22XL g306(.A0 (n_9), .A1 (INP[2]), .B0 (OUT[2]), .B1 (n_8), .Y
       (n_6));
  AOI22XL g311(.A0 (n_3), .A1 (rightInp), .B0 (n_2), .B1 (INP[1]), .Y
       (n_5));
  AOI22XL g310(.A0 (n_3), .A1 (INP[0]), .B0 (n_2), .B1 (INP[2]), .Y
       (n_4));
  AOI22XL g309(.A0 (n_3), .A1 (INP[2]), .B0 (n_2), .B1 (leftInp), .Y
       (n_1));
  AOI22XL g307(.A0 (n_3), .A1 (INP[1]), .B0 (n_2), .B1 (INP[3]), .Y
       (n_0));
  NOR2BXL g314(.AN (select[1]), .B (select[0]), .Y (n_3));
  AND2X1 g315(.A (select[0]), .B (select[1]), .Y (n_8));
  NOR2XL g316(.A (select[0]), .B (select[1]), .Y (n_9));
  NOR2BXL g317(.AN (select[0]), .B (select[1]), .Y (n_2));
endmodule

