
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 15 2019 08:52:02 IST (Sep 15 2019 03:22:02 UTC)

// Verification Directory fv/decoder3x8 

module decoder1x2_1(a0, a1, x0, en);
  input x0, en;
  output a0, a1;
  wire x0, en;
  wire a0, a1;
  NOR2BXL g18(.AN (en), .B (x0), .Y (a0));
  AND2X1 g19(.A (en), .B (x0), .Y (a1));
endmodule

module decoder2x4(a0, a1, a2, a3, x0, x1, en);
  input x0, x1, en;
  output a0, a1, a2, a3;
  wire x0, x1, en;
  wire a0, a1, a2, a3;
  decoder1x2_1 Decoder1x2_2(.a0 (a0), .a1 (a1), .x0 (x0), .en (en));
endmodule

module decoder1x2_3(a0, a1, x0, en);
  input x0, en;
  output a0, a1;
  wire x0, en;
  wire a0, a1;
  NOR2BXL g18(.AN (en), .B (x0), .Y (a0));
  AND2X1 g19(.A (x0), .B (en), .Y (a1));
endmodule

module decoder1x2_4(a0, a1, x0, en);
  input x0, en;
  output a0, a1;
  wire x0, en;
  wire a0, a1;
  NOR2BXL g18(.AN (en), .B (x0), .Y (a0));
  AND2XL g19(.A (x0), .B (en), .Y (a1));
endmodule

module decoder1x2_5(a0, a1, x0, en);
  input x0, en;
  output a0, a1;
  wire x0, en;
  wire a0, a1;
  NOR2BXL g18(.AN (en), .B (x0), .Y (a0));
  AND2XL g19(.A (x0), .B (en), .Y (a1));
endmodule

module decoder2x4_1(a0, a1, a2, a3, x0, x1, en);
  input x0, x1, en;
  output a0, a1, a2, a3;
  wire x0, x1, en;
  wire a0, a1, a2, a3;
  wire out1, out2;
  decoder1x2_3 Decoder1x2_1(.a0 (out1), .a1 (out2), .x0 (x1), .en (en));
  decoder1x2_4 Decoder1x2_2(.a0 (a0), .a1 (a1), .x0 (x0), .en (out1));
  decoder1x2_5 Decoder1x2_3(.a0 (a2), .a1 (a3), .x0 (x0), .en (out2));
endmodule

module decoder1x2_6(a0, a1, x0, en);
  input x0, en;
  output a0, a1;
  wire x0, en;
  wire a0, a1;
  NOR2BXL g18(.AN (en), .B (x0), .Y (a0));
  AND2X1 g19(.A (x0), .B (en), .Y (a1));
endmodule

module decoder1x2_7(a0, a1, x0, en);
  input x0, en;
  output a0, a1;
  wire x0, en;
  wire a0, a1;
  NOR2BXL g18(.AN (en), .B (x0), .Y (a0));
  AND2XL g19(.A (x0), .B (en), .Y (a1));
endmodule

module decoder1x2_8(a0, a1, x0, en);
  input x0, en;
  output a0, a1;
  wire x0, en;
  wire a0, a1;
  NOR2BXL g18(.AN (en), .B (x0), .Y (a0));
  AND2XL g19(.A (x0), .B (en), .Y (a1));
endmodule

module decoder2x4_2(a0, a1, a2, a3, x0, x1, en);
  input x0, x1, en;
  output a0, a1, a2, a3;
  wire x0, x1, en;
  wire a0, a1, a2, a3;
  wire out1, out2;
  decoder1x2_6 Decoder1x2_1(.a0 (out1), .a1 (out2), .x0 (x1), .en (en));
  decoder1x2_7 Decoder1x2_2(.a0 (a0), .a1 (a1), .x0 (x0), .en (out1));
  decoder1x2_8 Decoder1x2_3(.a0 (a2), .a1 (a3), .x0 (x0), .en (out2));
endmodule

module decoder3x8(a0, a1, a2, a3, a4, a5, a6, a7, x0, x1, x2, en);
  input x0, x1, x2, en;
  output a0, a1, a2, a3, a4, a5, a6, a7;
  wire x0, x1, x2, en;
  wire a0, a1, a2, a3, a4, a5, a6, a7;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED_HIER_Z, out1, out2;
  decoder2x4 Decoder2x4_1(.a0 (out1), .a1 (out2), .a2 (UNCONNECTED),
       .a3 (UNCONNECTED0), .x0 (x2), .x1 (UNCONNECTED_HIER_Z), .en
       (en));
  decoder2x4_1 Decoder2x4_2(.a0 (a0), .a1 (a1), .a2 (a2), .a3 (a3), .x0
       (x0), .x1 (x1), .en (out1));
  decoder2x4_2 Decoder2x4_3(.a0 (a4), .a1 (a5), .a2 (a6), .a3 (a7), .x0
       (x0), .x1 (x1), .en (out2));
endmodule

