
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 27 2019 22:19:24 IST (Sep 27 2019 16:49:24 UTC)

// Verification Directory fv/cla16bit 

module cla4bit(a, b, c, sum, c_out);
  input [3:0] a, b;
  input c;
  output [3:0] sum;
  output c_out;
  wire [3:0] a, b;
  wire c;
  wire [3:0] sum;
  wire c_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_7, n_8;
  wire n_10, n_11, n_13;
  OAI21XL g163(.A0 (n_13), .A1 (n_5), .B0 (n_0), .Y (c_out));
  MXI2XL g164(.A (n_3), .B (n_5), .S0 (n_13), .Y (sum[3]));
  AOI22XL g165(.A0 (n_11), .A1 (n_2), .B0 (a[2]), .B1 (b[2]), .Y
       (n_13));
  MXI2XL g166(.A (n_10), .B (n_11), .S0 (n_2), .Y (sum[2]));
  CLKINVX1 g167(.A (n_10), .Y (n_11));
  AOI22XL g168(.A0 (n_8), .A1 (n_4), .B0 (a[1]), .B1 (b[1]), .Y (n_10));
  MXI2XL g169(.A (n_7), .B (n_8), .S0 (n_4), .Y (sum[1]));
  CLKINVX1 g170(.A (n_7), .Y (n_8));
  AOI22XL g171(.A0 (n_1), .A1 (c), .B0 (a[0]), .B1 (b[0]), .Y (n_7));
  CLKXOR2X1 g172(.A (c), .B (n_1), .Y (sum[0]));
  CLKINVX1 g173(.A (n_3), .Y (n_5));
  CLKXOR2X1 g174(.A (b[1]), .B (a[1]), .Y (n_4));
  CLKXOR2X1 g175(.A (b[3]), .B (a[3]), .Y (n_3));
  CLKXOR2X1 g176(.A (b[2]), .B (a[2]), .Y (n_2));
  CLKXOR2X1 g177(.A (b[0]), .B (a[0]), .Y (n_1));
  NAND2XL g178(.A (b[3]), .B (a[3]), .Y (n_0));
endmodule

module cla4bit_1(a, b, c, sum, c_out);
  input [3:0] a, b;
  input c;
  output [3:0] sum;
  output c_out;
  wire [3:0] a, b;
  wire c;
  wire [3:0] sum;
  wire c_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_7, n_8;
  wire n_10, n_11, n_13;
  OAI21XL g163(.A0 (n_13), .A1 (n_5), .B0 (n_0), .Y (c_out));
  MXI2XL g164(.A (n_3), .B (n_5), .S0 (n_13), .Y (sum[3]));
  AOI22XL g165(.A0 (n_11), .A1 (n_2), .B0 (a[2]), .B1 (b[2]), .Y
       (n_13));
  MXI2XL g166(.A (n_10), .B (n_11), .S0 (n_2), .Y (sum[2]));
  CLKINVX1 g167(.A (n_10), .Y (n_11));
  AOI22XL g168(.A0 (n_8), .A1 (n_4), .B0 (a[1]), .B1 (b[1]), .Y (n_10));
  MXI2XL g169(.A (n_7), .B (n_8), .S0 (n_4), .Y (sum[1]));
  CLKINVX1 g170(.A (n_7), .Y (n_8));
  AOI22XL g171(.A0 (c), .A1 (n_1), .B0 (a[0]), .B1 (b[0]), .Y (n_7));
  CLKXOR2X1 g172(.A (n_1), .B (c), .Y (sum[0]));
  CLKINVX1 g173(.A (n_3), .Y (n_5));
  CLKXOR2X1 g174(.A (b[1]), .B (a[1]), .Y (n_4));
  CLKXOR2X1 g175(.A (b[3]), .B (a[3]), .Y (n_3));
  CLKXOR2X1 g176(.A (b[2]), .B (a[2]), .Y (n_2));
  CLKXOR2X1 g177(.A (b[0]), .B (a[0]), .Y (n_1));
  NAND2XL g178(.A (b[3]), .B (a[3]), .Y (n_0));
endmodule

module cla4bit_2(a, b, c, sum, c_out);
  input [3:0] a, b;
  input c;
  output [3:0] sum;
  output c_out;
  wire [3:0] a, b;
  wire c;
  wire [3:0] sum;
  wire c_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_7, n_8;
  wire n_10, n_11, n_13;
  OAI21XL g163(.A0 (n_13), .A1 (n_5), .B0 (n_0), .Y (c_out));
  MXI2XL g164(.A (n_3), .B (n_5), .S0 (n_13), .Y (sum[3]));
  AOI22XL g165(.A0 (n_11), .A1 (n_2), .B0 (a[2]), .B1 (b[2]), .Y
       (n_13));
  MXI2XL g166(.A (n_10), .B (n_11), .S0 (n_2), .Y (sum[2]));
  CLKINVX1 g167(.A (n_10), .Y (n_11));
  AOI22XL g168(.A0 (n_8), .A1 (n_4), .B0 (a[1]), .B1 (b[1]), .Y (n_10));
  MXI2XL g169(.A (n_7), .B (n_8), .S0 (n_4), .Y (sum[1]));
  CLKINVX1 g170(.A (n_7), .Y (n_8));
  AOI22XL g171(.A0 (c), .A1 (n_1), .B0 (a[0]), .B1 (b[0]), .Y (n_7));
  CLKXOR2X1 g172(.A (n_1), .B (c), .Y (sum[0]));
  CLKINVX1 g173(.A (n_3), .Y (n_5));
  CLKXOR2X1 g174(.A (b[1]), .B (a[1]), .Y (n_4));
  CLKXOR2X1 g175(.A (b[3]), .B (a[3]), .Y (n_3));
  CLKXOR2X1 g176(.A (b[2]), .B (a[2]), .Y (n_2));
  CLKXOR2X1 g177(.A (b[0]), .B (a[0]), .Y (n_1));
  NAND2XL g178(.A (b[3]), .B (a[3]), .Y (n_0));
endmodule

module cla4bit_3(a, b, c, sum, c_out);
  input [3:0] a, b;
  input c;
  output [3:0] sum;
  output c_out;
  wire [3:0] a, b;
  wire c;
  wire [3:0] sum;
  wire c_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_7, n_8;
  wire n_10, n_11, n_13;
  OAI21XL g163(.A0 (n_13), .A1 (n_5), .B0 (n_0), .Y (c_out));
  MXI2XL g164(.A (n_3), .B (n_5), .S0 (n_13), .Y (sum[3]));
  AOI22XL g165(.A0 (n_11), .A1 (n_2), .B0 (a[2]), .B1 (b[2]), .Y
       (n_13));
  MXI2XL g166(.A (n_10), .B (n_11), .S0 (n_2), .Y (sum[2]));
  CLKINVX1 g167(.A (n_10), .Y (n_11));
  AOI22XL g168(.A0 (n_8), .A1 (n_4), .B0 (a[1]), .B1 (b[1]), .Y (n_10));
  MXI2XL g169(.A (n_7), .B (n_8), .S0 (n_4), .Y (sum[1]));
  CLKINVX1 g170(.A (n_7), .Y (n_8));
  AOI22XL g171(.A0 (c), .A1 (n_1), .B0 (a[0]), .B1 (b[0]), .Y (n_7));
  CLKXOR2X1 g172(.A (n_1), .B (c), .Y (sum[0]));
  CLKINVX1 g173(.A (n_3), .Y (n_5));
  CLKXOR2X1 g174(.A (b[1]), .B (a[1]), .Y (n_4));
  CLKXOR2X1 g175(.A (b[3]), .B (a[3]), .Y (n_3));
  CLKXOR2X1 g176(.A (b[2]), .B (a[2]), .Y (n_2));
  CLKXOR2X1 g177(.A (b[0]), .B (a[0]), .Y (n_1));
  NAND2XL g178(.A (b[3]), .B (a[3]), .Y (n_0));
endmodule

module cla16bit(a, b, c, s_out, c_out);
  input [15:0] a, b;
  input c;
  output [15:0] s_out;
  output c_out;
  wire [15:0] a, b;
  wire c;
  wire [15:0] s_out;
  wire c_out;
  wire carry0, carry1, carry2;
  cla4bit cla1(a[3:0], b[3:0], c, s_out[3:0], carry0);
  cla4bit_1 cla2(a[7:4], b[7:4], carry0, s_out[7:4], carry1);
  cla4bit_2 cla3(a[11:8], b[11:8], carry1, s_out[11:8], carry2);
  cla4bit_3 cla4(a[15:12], b[15:12], carry2, s_out[15:12], c_out);
endmodule

