
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Oct  2 2019 00:31:05 IST (Oct  1 2019 19:01:05 UTC)

// Verification Directory fv/cla16bit 

module cla4bit(a, b, c, sum);
  input [3:0] a, b;
  input c;
  output [3:0] sum;
  wire [3:0] a, b;
  wire c;
  wire [3:0] sum;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_8, n_9;
  wire n_11, n_12;
  OAI21XL g142(.A0 (n_11), .A1 (n_3), .B0 (n_12), .Y (sum[3]));
  NAND2XL g143(.A (n_3), .B (n_11), .Y (n_12));
  AOI22XL g144(.A0 (n_9), .A1 (n_1), .B0 (a[2]), .B1 (b[2]), .Y (n_11));
  MXI2XL g145(.A (n_8), .B (n_9), .S0 (n_1), .Y (sum[2]));
  CLKINVX1 g146(.A (n_8), .Y (n_9));
  AOI22XL g147(.A0 (n_6), .A1 (n_2), .B0 (a[1]), .B1 (b[1]), .Y (n_8));
  MXI2XL g148(.A (n_5), .B (n_6), .S0 (n_2), .Y (sum[1]));
  CLKINVX1 g149(.A (n_5), .Y (n_6));
  AOI22XL g150(.A0 (n_0), .A1 (c), .B0 (a[0]), .B1 (b[0]), .Y (n_5));
  CLKXOR2X1 g151(.A (c), .B (n_0), .Y (sum[0]));
  CLKXOR2X1 g152(.A (b[3]), .B (a[3]), .Y (n_3));
  CLKXOR2X1 g153(.A (b[1]), .B (a[1]), .Y (n_2));
  CLKXOR2X1 g154(.A (b[2]), .B (a[2]), .Y (n_1));
  CLKXOR2X1 g155(.A (b[0]), .B (a[0]), .Y (n_0));
endmodule

module cla4bit_1(a, b, c, sum);
  input [3:0] a, b;
  input c;
  output [3:0] sum;
  wire [3:0] a, b;
  wire c;
  wire [3:0] sum;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_8, n_9;
  wire n_11, n_12;
  OAI21XL g142(.A0 (n_11), .A1 (n_3), .B0 (n_12), .Y (sum[3]));
  NAND2XL g143(.A (n_3), .B (n_11), .Y (n_12));
  AOI22XL g144(.A0 (n_9), .A1 (n_1), .B0 (a[2]), .B1 (b[2]), .Y (n_11));
  MXI2XL g145(.A (n_8), .B (n_9), .S0 (n_1), .Y (sum[2]));
  CLKINVX1 g146(.A (n_8), .Y (n_9));
  AOI22XL g147(.A0 (n_6), .A1 (n_2), .B0 (a[1]), .B1 (b[1]), .Y (n_8));
  MXI2XL g148(.A (n_5), .B (n_6), .S0 (n_2), .Y (sum[1]));
  CLKINVX1 g149(.A (n_5), .Y (n_6));
  AOI22XL g150(.A0 (c), .A1 (n_0), .B0 (a[0]), .B1 (b[0]), .Y (n_5));
  CLKXOR2X1 g151(.A (n_0), .B (c), .Y (sum[0]));
  CLKXOR2X1 g152(.A (b[3]), .B (a[3]), .Y (n_3));
  CLKXOR2X1 g153(.A (b[1]), .B (a[1]), .Y (n_2));
  CLKXOR2X1 g154(.A (b[2]), .B (a[2]), .Y (n_1));
  CLKXOR2X1 g155(.A (b[0]), .B (a[0]), .Y (n_0));
endmodule

module cla4bit_2(a, b, c, sum);
  input [3:0] a, b;
  input c;
  output [3:0] sum;
  wire [3:0] a, b;
  wire c;
  wire [3:0] sum;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_8, n_9;
  wire n_11, n_12;
  OAI21XL g142(.A0 (n_11), .A1 (n_3), .B0 (n_12), .Y (sum[3]));
  NAND2XL g143(.A (n_3), .B (n_11), .Y (n_12));
  AOI22XL g144(.A0 (n_9), .A1 (n_1), .B0 (a[2]), .B1 (b[2]), .Y (n_11));
  MXI2XL g145(.A (n_8), .B (n_9), .S0 (n_1), .Y (sum[2]));
  CLKINVX1 g146(.A (n_8), .Y (n_9));
  AOI22XL g147(.A0 (n_6), .A1 (n_2), .B0 (a[1]), .B1 (b[1]), .Y (n_8));
  MXI2XL g148(.A (n_5), .B (n_6), .S0 (n_2), .Y (sum[1]));
  CLKINVX1 g149(.A (n_5), .Y (n_6));
  AOI22XL g150(.A0 (c), .A1 (n_0), .B0 (a[0]), .B1 (b[0]), .Y (n_5));
  CLKXOR2X1 g151(.A (n_0), .B (c), .Y (sum[0]));
  CLKXOR2X1 g152(.A (b[3]), .B (a[3]), .Y (n_3));
  CLKXOR2X1 g153(.A (b[1]), .B (a[1]), .Y (n_2));
  CLKXOR2X1 g154(.A (b[2]), .B (a[2]), .Y (n_1));
  CLKXOR2X1 g155(.A (b[0]), .B (a[0]), .Y (n_0));
endmodule

module cla4bit_3(a, b, c, sum);
  input [3:0] a, b;
  input c;
  output [3:0] sum;
  wire [3:0] a, b;
  wire c;
  wire [3:0] sum;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_8, n_9;
  wire n_11, n_12;
  OAI21XL g142(.A0 (n_11), .A1 (n_3), .B0 (n_12), .Y (sum[3]));
  NAND2XL g143(.A (n_3), .B (n_11), .Y (n_12));
  AOI22XL g144(.A0 (n_9), .A1 (n_1), .B0 (a[2]), .B1 (b[2]), .Y (n_11));
  MXI2XL g145(.A (n_8), .B (n_9), .S0 (n_1), .Y (sum[2]));
  CLKINVX1 g146(.A (n_8), .Y (n_9));
  AOI22XL g147(.A0 (n_6), .A1 (n_2), .B0 (a[1]), .B1 (b[1]), .Y (n_8));
  MXI2XL g148(.A (n_5), .B (n_6), .S0 (n_2), .Y (sum[1]));
  CLKINVX1 g149(.A (n_5), .Y (n_6));
  AOI22XL g150(.A0 (c), .A1 (n_0), .B0 (a[0]), .B1 (b[0]), .Y (n_5));
  CLKXOR2X1 g151(.A (n_0), .B (c), .Y (sum[0]));
  CLKXOR2X1 g152(.A (b[3]), .B (a[3]), .Y (n_3));
  CLKXOR2X1 g153(.A (b[1]), .B (a[1]), .Y (n_2));
  CLKXOR2X1 g154(.A (b[2]), .B (a[2]), .Y (n_1));
  CLKXOR2X1 g155(.A (b[0]), .B (a[0]), .Y (n_0));
endmodule

module cla16bit(a, b, c, s_out, c_out);
  input [15:0] a, b;
  input c;
  output [15:0] s_out;
  output c_out;
  wire [15:0] a, b;
  wire c;
  wire [15:0] s_out;
  wire c_out;
  wire \carry[4] , \carry[8] , \carry[12] , n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  cla4bit cla1(a[3:0], b[3:0], c, s_out[3:0]);
  cla4bit_1 cla2(a[7:4], b[7:4], \carry[4] , s_out[7:4]);
  cla4bit_2 cla3(a[11:8], b[11:8], \carry[8] , s_out[11:8]);
  cla4bit_3 cla4(a[15:12], b[15:12], \carry[12] , s_out[15:12]);
  OAI2BB1XL g733(.A0N (a[15]), .A1N (n_26), .B0 (n_27), .Y (c_out));
  OAI21XL g734(.A0 (n_26), .A1 (a[15]), .B0 (b[15]), .Y (n_27));
  OAI2BB1XL g735(.A0N (b[14]), .A1N (n_24), .B0 (n_25), .Y (n_26));
  OAI21XL g736(.A0 (n_24), .A1 (b[14]), .B0 (a[14]), .Y (n_25));
  OAI2BB1XL g737(.A0N (a[13]), .A1N (n_22), .B0 (n_23), .Y (n_24));
  OAI21XL g738(.A0 (n_22), .A1 (a[13]), .B0 (b[13]), .Y (n_23));
  OAI2BB1XL g739(.A0N (a[12]), .A1N (\carry[12] ), .B0 (n_21), .Y
       (n_22));
  OAI21XL g740(.A0 (\carry[12] ), .A1 (a[12]), .B0 (b[12]), .Y (n_21));
  OAI2BB1XL g741(.A0N (a[11]), .A1N (n_19), .B0 (n_20), .Y (\carry[12]
       ));
  OAI21XL g742(.A0 (n_19), .A1 (a[11]), .B0 (b[11]), .Y (n_20));
  OAI2BB1XL g743(.A0N (a[10]), .A1N (n_17), .B0 (n_18), .Y (n_19));
  OAI21XL g744(.A0 (n_17), .A1 (a[10]), .B0 (b[10]), .Y (n_18));
  OAI2BB1XL g745(.A0N (a[9]), .A1N (n_15), .B0 (n_16), .Y (n_17));
  OAI21XL g746(.A0 (n_15), .A1 (a[9]), .B0 (b[9]), .Y (n_16));
  OAI2BB1XL g747(.A0N (a[8]), .A1N (\carry[8] ), .B0 (n_14), .Y (n_15));
  OAI21XL g748(.A0 (\carry[8] ), .A1 (a[8]), .B0 (b[8]), .Y (n_14));
  OAI2BB1XL g749(.A0N (b[7]), .A1N (a[7]), .B0 (n_13), .Y (\carry[8] ));
  OAI21XL g750(.A0 (a[7]), .A1 (b[7]), .B0 (n_12), .Y (n_13));
  OAI2BB1XL g751(.A0N (b[6]), .A1N (a[6]), .B0 (n_11), .Y (n_12));
  OAI21XL g752(.A0 (a[6]), .A1 (b[6]), .B0 (n_10), .Y (n_11));
  OAI2BB1XL g753(.A0N (a[5]), .A1N (n_8), .B0 (n_9), .Y (n_10));
  OAI21XL g754(.A0 (n_8), .A1 (a[5]), .B0 (b[5]), .Y (n_9));
  OAI2BB1XL g755(.A0N (a[4]), .A1N (\carry[4] ), .B0 (n_7), .Y (n_8));
  OAI21XL g756(.A0 (\carry[4] ), .A1 (a[4]), .B0 (b[4]), .Y (n_7));
  OAI2BB1XL g757(.A0N (a[3]), .A1N (n_5), .B0 (n_6), .Y (\carry[4] ));
  OAI21XL g758(.A0 (n_5), .A1 (a[3]), .B0 (b[3]), .Y (n_6));
  OAI2BB1XL g759(.A0N (b[2]), .A1N (a[2]), .B0 (n_4), .Y (n_5));
  OAI21XL g760(.A0 (a[2]), .A1 (b[2]), .B0 (n_3), .Y (n_4));
  OAI2BB1XL g761(.A0N (a[1]), .A1N (n_1), .B0 (n_2), .Y (n_3));
  OAI21XL g762(.A0 (n_1), .A1 (a[1]), .B0 (b[1]), .Y (n_2));
  OAI2BB1XL g763(.A0N (c), .A1N (b[0]), .B0 (n_0), .Y (n_1));
  OAI21XL g764(.A0 (b[0]), .A1 (c), .B0 (a[0]), .Y (n_0));
endmodule

