
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 15 2019 08:48:04 IST (Sep 15 2019 03:18:04 UTC)

// Verification Directory fv/demux1x8 

module demux1x2_1(a, b, x0, in);
  input x0, in;
  output a, b;
  wire x0, in;
  wire a, b;
  NOR2BXL g16(.AN (in), .B (x0), .Y (a));
  AND2X1 g17(.A (in), .B (x0), .Y (b));
endmodule

module demux1x4(a, b, c, d, x0, x1, in);
  input x0, x1, in;
  output a, b, c, d;
  wire x0, x1, in;
  wire a, b, c, d;
  demux1x2_1 Demux1x2_2(.a (a), .b (b), .x0 (x0), .in (in));
endmodule

module demux1x2_3(a, b, x0, in);
  input x0, in;
  output a, b;
  wire x0, in;
  wire a, b;
  NOR2BXL g16(.AN (in), .B (x0), .Y (a));
  AND2X1 g17(.A (x0), .B (in), .Y (b));
endmodule

module demux1x2_4(a, b, x0, in);
  input x0, in;
  output a, b;
  wire x0, in;
  wire a, b;
  NOR2BXL g16(.AN (in), .B (x0), .Y (a));
  AND2XL g17(.A (x0), .B (in), .Y (b));
endmodule

module demux1x2_5(a, b, x0, in);
  input x0, in;
  output a, b;
  wire x0, in;
  wire a, b;
  NOR2BXL g16(.AN (in), .B (x0), .Y (a));
  AND2XL g17(.A (x0), .B (in), .Y (b));
endmodule

module demux1x4_1(a, b, c, d, x0, x1, in);
  input x0, x1, in;
  output a, b, c, d;
  wire x0, x1, in;
  wire a, b, c, d;
  wire out1, out2;
  demux1x2_3 Demux1x2_1(.a (out1), .b (out2), .x0 (x1), .in (in));
  demux1x2_4 Demux1x2_2(.a (a), .b (b), .x0 (x0), .in (out1));
  demux1x2_5 Demux1x2_3(.a (c), .b (d), .x0 (x0), .in (out2));
endmodule

module demux1x2_6(a, b, x0, in);
  input x0, in;
  output a, b;
  wire x0, in;
  wire a, b;
  NOR2BXL g16(.AN (in), .B (x0), .Y (a));
  AND2X1 g17(.A (x0), .B (in), .Y (b));
endmodule

module demux1x2_7(a, b, x0, in);
  input x0, in;
  output a, b;
  wire x0, in;
  wire a, b;
  NOR2BXL g16(.AN (in), .B (x0), .Y (a));
  AND2XL g17(.A (x0), .B (in), .Y (b));
endmodule

module demux1x2_8(a, b, x0, in);
  input x0, in;
  output a, b;
  wire x0, in;
  wire a, b;
  NOR2BXL g16(.AN (in), .B (x0), .Y (a));
  AND2XL g17(.A (x0), .B (in), .Y (b));
endmodule

module demux1x4_2(a, b, c, d, x0, x1, in);
  input x0, x1, in;
  output a, b, c, d;
  wire x0, x1, in;
  wire a, b, c, d;
  wire out1, out2;
  demux1x2_6 Demux1x2_1(.a (out1), .b (out2), .x0 (x1), .in (in));
  demux1x2_7 Demux1x2_2(.a (a), .b (b), .x0 (x0), .in (out1));
  demux1x2_8 Demux1x2_3(.a (c), .b (d), .x0 (x0), .in (out2));
endmodule

module demux1x8(a, b, c, d, e, f, g, h, x0, x1, x2, in);
  input x0, x1, x2, in;
  output a, b, c, d, e, f, g, h;
  wire x0, x1, x2, in;
  wire a, b, c, d, e, f, g, h;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED_HIER_Z, out1, out2;
  demux1x4 Demux1x4_1(.a (out1), .b (out2), .c (UNCONNECTED), .d
       (UNCONNECTED0), .x0 (x2), .x1 (UNCONNECTED_HIER_Z), .in (in));
  demux1x4_1 Demux1x4_2(.a (a), .b (b), .c (c), .d (d), .x0 (x0), .x1
       (x1), .in (out1));
  demux1x4_2 Demux1x4_3(.a (e), .b (f), .c (g), .d (h), .x0 (x0), .x1
       (x1), .in (out2));
endmodule

