/*
###############################################################
#  Generated by:      Cadence Innovus 16.21-s078_1
#  OS:                Linux x86_64(Host ID client03)
#  Generated on:      Thu Sep  5 22:56:54 2019
#  Design:            f1
#  Command:           saveNetlist f1_netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 18:13:50 IST (Sep  5 2019 12:43:50 UTC)
// Verification Directory fv/f1 
module f1 (
	a, 
	b, 
	c, 
	d, 
	out);
   input a;
   input b;
   input c;
   input d;
   output out;

   AO22X1 g20 (.A0(d),
	.A1(c),
	.B0(b),
	.B1(a),
	.Y(out));
endmodule

