
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Nov  9 2019 19:02:45 IST (Nov  9 2019 13:32:45 UTC)

// Verification Directory fv/fsm 

module fsm(CLK, RESET, INP, OUT);
  input CLK, RESET, INP;
  output OUT;
  wire CLK, RESET, INP;
  wire OUT;
  wire [2:0] state;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_12, n_13, n_14, n_15, n_17, n_22, n_23;
  DFFRHQX1 OUT_reg(.RN (n_17), .CK (CLK), .D (n_15), .Q (OUT));
  OAI21XL g603(.A0 (n_14), .A1 (state[2]), .B0 (n_13), .Y (n_15));
  DFFRX1 \state_reg[2] (.RN (n_17), .CK (CLK), .D (n_23), .Q (n_4), .QN
       (state[2]));
  AOI21XL g604(.A0 (INP), .A1 (n_9), .B0 (OUT), .Y (n_13));
  NAND2XL g607(.A (n_6), .B (n_5), .Y (n_12));
  NAND2XL g610(.A (n_3), .B (n_1), .Y (n_14));
  OAI211XL g608(.A0 (n_4), .A1 (INP), .B0 (state[1]), .C0 (state[0]),
       .Y (n_8));
  OAI21XL g612(.A0 (state[2]), .A1 (n_6), .B0 (n_0), .Y (n_7));
  MXI2XL g613(.A (INP), .B (n_4), .S0 (n_3), .Y (n_5));
  NOR3XL g614(.A (state[1]), .B (state[2]), .C (n_3), .Y (n_9));
  NOR2XL g616(.A (INP), .B (n_6), .Y (n_1));
  INVXL g621(.A (INP), .Y (n_0));
  INVXL g619(.A (RESET), .Y (n_17));
  DFFRX1 \state_reg[1] (.RN (n_17), .CK (CLK), .D (n_7), .Q (state[1]),
       .QN (n_6));
  DFFRX1 \state_reg[0] (.RN (n_17), .CK (CLK), .D (n_22), .Q
       (state[0]), .QN (n_3));
  NAND4BXL g2(.AN (n_9), .B (n_8), .C (n_14), .D (n_12), .Y (n_22));
  NAND2BX1 g630(.AN (n_1), .B (state[2]), .Y (n_23));
endmodule

