
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Nov 10 2019 21:33:08 IST (Nov 10 2019 16:03:08 UTC)

// Verification Directory fv/fsm 

module fsm(CLK, RESET, ONE, ZERO, OUT);
  input CLK, RESET, ONE, ZERO;
  output OUT;
  wire CLK, RESET, ONE, ZERO;
  wire OUT;
  wire [3:0] state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, prev0;
  wire prev1;
  assign prev0 = 1'b0;
  assign prev1 = 1'b0;
  NOR4BXL g1302(.AN (state[3]), .B (state[1]), .C (state[2]), .D
       (state[0]), .Y (OUT));
  DFFQX1 \state_reg[0] (.CK (CLK), .D (n_30), .Q (state[0]));
  DFFQX1 \state_reg[3] (.CK (CLK), .D (n_29), .Q (state[3]));
  DFFQX1 \state_reg[2] (.CK (CLK), .D (n_28), .Q (state[2]));
  OAI222XL g1913(.A0 (state[1]), .A1 (n_23), .B0 (state[0]), .B1
       (n_20), .C0 (n_21), .C1 (n_0), .Y (n_30));
  DFFQX1 \state_reg[1] (.CK (CLK), .D (n_27), .Q (state[1]));
  NOR2XL g1915(.A (RESET), .B (n_26), .Y (n_29));
  NAND2XL g1916(.A (n_20), .B (n_25), .Y (n_28));
  OAI2BB1XL g1917(.A0N (state[1]), .A1N (n_18), .B0 (n_24), .Y (n_27));
  AOI31XL g1918(.A0 (n_16), .A1 (state[2]), .A2 (state[1]), .B0
       (state[3]), .Y (n_26));
  AOI222XL g1919(.A0 (state[0]), .A1 (n_14), .B0 (state[1]), .B1
       (n_11), .C0 (n_22), .C1 (state[2]), .Y (n_25));
  AOI32XL g1920(.A0 (n_16), .A1 (n_3), .A2 (n_5), .B0 (n_11), .B1
       (state[2]), .Y (n_24));
  DFFQX1 prev1_reg163(.CK (CLK), .D (n_19), .Q (prev1));
  AOI32XL g1922(.A0 (n_5), .A1 (n_6), .A2 (n_2), .B0 (n_1), .B1
       (state[2]), .Y (n_23));
  AOI21XL g1923(.A0 (state[1]), .A1 (n_12), .B0 (RESET), .Y (n_22));
  AOI221XL g1924(.A0 (n_9), .A1 (n_2), .B0 (n_7), .B1 (state[2]), .C0
       (state[3]), .Y (n_21));
  DFFQX1 prev0_reg160(.CK (CLK), .D (n_15), .Q (prev0));
  NOR2XL g1926(.A (RESET), .B (n_17), .Y (n_19));
  OAI22XL g1927(.A0 (n_12), .A1 (RESET), .B0 (n_0), .B1 (n_10), .Y
       (n_18));
  NAND3XL g1928(.A (state[1]), .B (n_2), .C (n_14), .Y (n_20));
  AOI2BB1XL g1930(.A0N (n_9), .A1N (state[3]), .B0 (prev1), .Y (n_17));
  NOR2XL g1931(.A (RESET), .B (n_13), .Y (n_15));
  MXI2XL g1932(.A (n_9), .B (n_7), .S0 (state[0]), .Y (n_16));
  AOI21XL g1934(.A0 (n_6), .A1 (n_4), .B0 (prev0), .Y (n_13));
  NOR2BXL g1935(.AN (n_5), .B (n_9), .Y (n_14));
  AOI21XL g1936(.A0 (n_8), .A1 (n_7), .B0 (state[3]), .Y (n_12));
  NOR3BXL g1937(.AN (n_5), .B (n_7), .C (state[0]), .Y (n_11));
  NOR2XL g1938(.A (n_7), .B (n_2), .Y (n_10));
  OR2X1 g1939(.A (n_8), .B (n_6), .Y (n_9));
  CLKINVX1 g1940(.A (n_7), .Y (n_6));
  NAND2BXL g1941(.AN (prev1), .B (ONE), .Y (n_8));
  NAND2BXL g1942(.AN (prev0), .B (ZERO), .Y (n_7));
  NOR2XL g1944(.A (RESET), .B (state[3]), .Y (n_5));
  CLKINVX1 g1945(.A (state[3]), .Y (n_4));
  CLKINVX1 g1947(.A (state[1]), .Y (n_3));
  CLKINVX1 g1948(.A (state[2]), .Y (n_2));
  NAND2BX1 g2(.AN (n_14), .B (n_0), .Y (n_1));
  NAND2BX1 g1949(.AN (RESET), .B (state[0]), .Y (n_0));
endmodule

