
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 18:29:54 IST (Sep  5 2019 12:59:54 UTC)

// Verification Directory fv/f2 

module f2(a, b, c, d, e, f, out);
  input a, b, c, d, e, f;
  output out;
  wire a, b, c, d, e, f;
  wire out;
  wire n_0;
  NOR2BXL g48(.AN (f), .B (n_0), .Y (out));
  AOI32XL g49(.A0 (c), .A1 (b), .A2 (a), .B0 (d), .B1 (e), .Y (n_0));
endmodule

