
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Oct 31 2019 19:42:12 IST (Oct 31 2019 14:12:12 UTC)

// Verification Directory fv/fft2 

module fft2(inp, rout_0, rout_1, rout_2, rout_3, iout_0, iout_1,
     iout_2, iout_3);
  input [3:0] inp;
  output [2:0] rout_0, rout_1, rout_2, rout_3, iout_0, iout_1, iout_2,
       iout_3;
  wire [3:0] inp;
  wire [2:0] rout_0, rout_1, rout_2, rout_3, iout_0, iout_1, iout_2,
       iout_3;
  wire n_0, n_1, n_2, n_4, n_5, n_6, n_8, n_10;
  assign iout_3[0] = iout_1[0];
  assign iout_3[1] = iout_3[2];
  assign iout_2[0] = 1'b0;
  assign iout_2[1] = 1'b0;
  assign iout_2[2] = 1'b0;
  assign iout_1[1] = iout_1[2];
  assign iout_0[0] = 1'b0;
  assign iout_0[1] = 1'b0;
  assign iout_0[2] = 1'b0;
  assign rout_3[0] = rout_1[0];
  assign rout_3[1] = rout_1[2];
  assign rout_3[2] = rout_1[2];
  assign rout_2[0] = rout_0[0];
  assign rout_1[1] = rout_1[2];
  OAI222XL g249(.A0 (n_8), .A1 (n_10), .B0 (n_2), .B1 (n_0), .C0 (n_5),
       .C1 (inp[0]), .Y (rout_0[1]));
  MXI2XL g251(.A (n_10), .B (rout_1[0]), .S0 (iout_1[0]), .Y
       (rout_0[0]));
  AO21X1 g250(.A0 (n_8), .A1 (n_6), .B0 (rout_2[2]), .Y (rout_2[1]));
  OAI32XL g252(.A0 (inp[0]), .A1 (inp[2]), .A2 (n_8), .B0 (n_6), .B1
       (n_5), .Y (rout_2[2]));
  INVXL g253(.A (rout_1[0]), .Y (n_10));
  OAI21XL g256(.A0 (n_1), .A1 (inp[2]), .B0 (n_4), .Y (rout_1[0]));
  INVXL g258(.A (n_4), .Y (rout_1[2]));
  NOR2XL g254(.A (n_5), .B (n_2), .Y (rout_0[2]));
  OR2X1 g255(.A (iout_3[2]), .B (iout_1[2]), .Y (iout_1[0]));
  NAND2XL g261(.A (inp[2]), .B (n_1), .Y (n_4));
  INVXL g257(.A (n_5), .Y (n_0));
  INVXL g262(.A (n_2), .Y (n_6));
  NOR2XL g264(.A (inp[1]), .B (inp[3]), .Y (n_8));
  NOR2BXL g263(.AN (inp[1]), .B (inp[3]), .Y (iout_1[2]));
  NAND2XL g265(.A (inp[0]), .B (inp[2]), .Y (n_2));
  NOR2BXL g259(.AN (inp[3]), .B (inp[1]), .Y (iout_3[2]));
  NAND2XL g260(.A (inp[1]), .B (inp[3]), .Y (n_5));
  INVXL g266(.A (inp[0]), .Y (n_1));
endmodule

