
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Oct 10 2019 22:22:09 IST (Oct 10 2019 16:52:09 UTC)

// Verification Directory fv/wallace 

module fulladder(a, b, c, s_out, c_out);
  input a, b, c;
  inout s_out, c_out;
  wire a, b, c;
  wire s_out, c_out;
  ADDHXL g22(.A (a), .B (b), .CO (c_out), .S (s_out));
endmodule

module fulladder_1(a, b, c, s_out, c_out);
  input a, b, c;
  inout s_out, c_out;
  wire a, b, c;
  wire s_out, c_out;
  ADDFX1 g55(.A (b), .B (a), .CI (c), .CO (c_out), .S (s_out));
endmodule

module fulladder_2(a, b, c, s_out, c_out);
  input a, b, c;
  inout s_out, c_out;
  wire a, b, c;
  wire s_out, c_out;
  ADDFX1 g55(.A (b), .B (a), .CI (c), .CO (c_out), .S (s_out));
endmodule

module fulladder_3(a, b, c, s_out, c_out);
  input a, b, c;
  inout s_out, c_out;
  wire a, b, c;
  wire s_out, c_out;
  ADDFX1 g55(.A (b), .B (a), .CI (c), .CO (c_out), .S (s_out));
endmodule

module fulladder_4(a, b, c, s_out, c_out);
  input a, b, c;
  inout s_out, c_out;
  wire a, b, c;
  wire s_out, c_out;
  ADDHXL g22(.A (a), .B (b), .CO (c_out), .S (s_out));
endmodule

module fulladder_5(a, b, c, s_out, c_out);
  input a, b, c;
  inout s_out, c_out;
  wire a, b, c;
  wire s_out, c_out;
  ADDHXL g22(.A (a), .B (b), .CO (c_out), .S (s_out));
endmodule

module fulladder_6(a, b, c, s_out, c_out);
  input a, b, c;
  inout s_out, c_out;
  wire a, b, c;
  wire s_out, c_out;
  ADDFX1 g55(.A (b), .B (a), .CI (c), .CO (c_out), .S (s_out));
endmodule

module fulladder_7(a, b, c, s_out, c_out);
  input a, b, c;
  inout s_out, c_out;
  wire a, b, c;
  wire s_out, c_out;
  ADDFX1 g55(.A (c), .B (a), .CI (b), .CO (c_out), .S (s_out));
endmodule

module fulladder_8(a, b, c, s_out, c_out);
  input a, b, c;
  inout s_out, c_out;
  wire a, b, c;
  wire s_out, c_out;
  ADDFX1 g55(.A (a), .B (c), .CI (b), .CO (c_out), .S (s_out));
endmodule

module fulladder_9(a, b, c, s_out, c_out);
  input a, b, c;
  inout s_out, c_out;
  wire a, b, c;
  wire s_out, c_out;
  ADDFX1 g55(.A (a), .B (c), .CI (b), .CO (c_out), .S (s_out));
endmodule

module fulladder_10(a, b, c, s_out, c_out);
  input a, b, c;
  inout s_out, c_out;
  wire a, b, c;
  wire s_out, c_out;
  ADDHXL g22(.A (a), .B (b), .CO (c_out), .S (s_out));
endmodule

module fulladder_11(a, b, c, s_out, c_out);
  input a, b, c;
  inout s_out, c_out;
  wire a, b, c;
  wire s_out, c_out;
  ADDHXL g22(.A (a), .B (b), .CO (c_out), .S (s_out));
endmodule

module fulladder_12(a, b, c, s_out, c_out);
  input a, b, c;
  inout s_out, c_out;
  wire a, b, c;
  wire s_out, c_out;
  ADDHXL g22(.A (a), .B (b), .CO (c_out), .S (s_out));
endmodule

module fulladder_13(a, b, c, s_out, c_out);
  input a, b, c;
  inout s_out, c_out;
  wire a, b, c;
  wire s_out, c_out;
  ADDHXL g22(.A (a), .B (b), .CO (c_out), .S (s_out));
endmodule

module fulladder_14(a, b, c, s_out, c_out);
  input a, b, c;
  inout s_out, c_out;
  wire a, b, c;
  wire s_out, c_out;
  ADDHXL g22(.A (b), .B (a), .CO (c_out), .S (s_out));
endmodule

module wallace(a, b, out);
  input [3:0] a, b;
  output [7:0] out;
  wire [3:0] a, b;
  wire [7:0] out;
  wire [6:0] p0;
  wire [6:0] p1;
  wire [6:0] p2;
  wire [6:0] p3;
  wire UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1,
       UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z3, UNCONNECTED_HIER_Z4,
       UNCONNECTED_HIER_Z5, UNCONNECTED_HIER_Z6;
  wire c11, c12, c13, c14, c15, c22, c23, c24;
  wire c25, c26, c32, c34, c35, c36, c37, s12;
  wire s13, s14, s15, s23, s24, s25, s26;
  fulladder fa11(p0[1], p1[0], UNCONNECTED_HIER_Z, out[1], c11);
  fulladder_1 fa12(p0[2], p1[1], p2[0], s12, c12);
  fulladder_2 fa13(p0[3], p1[2], p2[1], s13, c13);
  fulladder_3 fa14(p1[3], p2[2], p3[1], s14, c14);
  fulladder_4 fa15(p2[3], p3[2], UNCONNECTED_HIER_Z0, s15, c15);
  fulladder_5 fa22(c11, s12, UNCONNECTED_HIER_Z1, out[2], c22);
  fulladder_6 fa23(p3[0], c12, s13, s23, c23);
  fulladder_7 fa24(c13, c32, s14, s24, c24);
  fulladder_8 fa25(c14, c24, s15, s25, c25);
  fulladder_9 fa26(c15, c25, p3[3], s26, c26);
  fulladder_10 fa32(c22, s23, UNCONNECTED_HIER_Z2, out[3], c32);
  fulladder_11 fa34(c23, s24, UNCONNECTED_HIER_Z3, out[4], c34);
  fulladder_12 fa35(c34, s25, UNCONNECTED_HIER_Z4, out[5], c35);
  fulladder_13 fa36(c35, s26, UNCONNECTED_HIER_Z5, out[6], c36);
  fulladder_14 fa37(c36, c26, UNCONNECTED_HIER_Z6, out[7], c37);
  AND2X1 g120(.A (b[1]), .B (a[2]), .Y (p1[2]));
  AND2X1 g121(.A (b[1]), .B (a[1]), .Y (p1[1]));
  AND2X1 g122(.A (b[1]), .B (a[0]), .Y (p1[0]));
  AND2X1 g123(.A (b[3]), .B (a[1]), .Y (p3[1]));
  AND2XL g124(.A (b[0]), .B (a[0]), .Y (out[0]));
  AND2X1 g125(.A (b[2]), .B (a[3]), .Y (p2[3]));
  AND2X1 g126(.A (b[1]), .B (a[3]), .Y (p1[3]));
  AND2X1 g127(.A (b[2]), .B (a[0]), .Y (p2[0]));
  AND2X1 g128(.A (b[2]), .B (a[2]), .Y (p2[2]));
  AND2X1 g129(.A (b[2]), .B (a[1]), .Y (p2[1]));
  AND2X1 g130(.A (b[3]), .B (a[0]), .Y (p3[0]));
  AND2X1 g131(.A (b[0]), .B (a[3]), .Y (p0[3]));
  AND2X1 g132(.A (b[3]), .B (a[3]), .Y (p3[3]));
  AND2X1 g133(.A (b[0]), .B (a[1]), .Y (p0[1]));
  AND2X1 g134(.A (b[3]), .B (a[2]), .Y (p3[2]));
  AND2X1 g135(.A (b[0]), .B (a[2]), .Y (p0[2]));
endmodule

